### PR TITLE
feat: enable deployment annotations

### PR DESCRIPTION
**Pull request by MattiDeGrauwe**
This PR allows deployment annotations to be set for prometheus-multi-tenant-proxy

### CODE REVIEW

**Comment by MattiDeGrauwe** [comment]
@angelbarrera92 any idea if we can proceed with this?

**Review by angelbarrera92 — APPROVED** [review]
Thanks!

**Comment by MattiDeGrauwe** [comment]
> Thanks!

Hello @angelbarrera92 , can we release this one? :smile:

**Comment by MattiDeGrauwe** [comment]
@angelbarrera92 can we release this one in 2.0.1? :)

**Pull request merged**
